### ISSUE TITLE
Windows 10 eccodes-python not returning values from installed Eccodes library

### ISSUE THREAD

**Issue by richard-meto** [ecmwf/eccodes-python#10]
Hi

On Windows 10 I have installed eccodes using conda and eccodes-python using pip. I have set the library paths in environment variables.

I obtained some validated bufr files for a Synop observation but when using the Python code example from the ECMWF website the code runs without throwing any exceptions and returns no data from the bufr file.

ECCODES is verified as installed from the selfcheck command.

`> C:\eccodes\eccodes\eccodes-master\examples\python>python -m eccodes selfcheck
Found: ecCodes v2.13.1.
Your system is ready.
 `
Running a sample Python bufr script: -

`C:\ProgramData\Miniconda3\python.exe C:/eccodes/eccodes/eccodes-master/examples/python/bufr_read_synop.py
message: 0

Process finished with exit code -1073741819 (0xC0000005)`

No errors are returned from the execution.

**Comment by dtip** [comment]
Hi @richard-meto - I'm fairly sure eccodes-python has never been tested on Windows. You might be interested in the thread here https://github.com/conda-forge/python-eccodes-feedstock/issues/52
where there's a discussion about adding the Windows build of eccodes-python to conda-forge.

**Comment by shahramn** [comment]
Windows is not fully supported
