### ISSUE TITLE
eccodes 2.37.0 does no longer work with ecmwflibs (0.6.3)

### ISSUE THREAD

**Issue by ghaarsma** [ecmwf/eccodes-python#102]
### What happened?

When upgrading from eccodes 1.7.1 to eccodes 2.37.0, the package stopped working with ecmwflibs (Python 3.11 on Windows 10)

### What are the steps to reproduce the bug?

```
(venv) PS C:\Users\gxvh\Python\cfgrib_test> python -m venv venv
(venv) PS C:\Users\gxvh\Python\cfgrib_test> .\venv\Scripts\Activate.ps1
(venv) PS C:\Users\gxvh\Python\cfgrib_test> pip install ecmwflibs eccodes==1.7.1

Collecting ecmwflibs
Collecting eccodes==1.7.1
Collecting numpy (from eccodes==1.7.1)
Collecting attrs (from eccodes==1.7.1)
Collecting cffi (from eccodes==1.7.1)
Collecting findlibs (from eccodes==1.7.1)
Collecting pycparser (from cffi->eccodes==1.7.1)
Building wheels for collected packages: findlibs
Successfully built findlibs
Installing collected packages: findlibs, pycparser, numpy, ecmwflibs, attrs, cffi, eccodes
Successfully installed attrs-24.2.0 cffi-1.17.1 eccodes-1.7.1 ecmwflibs-0.6.3 findlibs-0.0.5 numpy-2.1.1 pycparser-2.22

(venv) PS C:\Users\gxvh\Python\cfgrib_test> python
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import eccodes
>>> exit()


(venv) PS C:\Users\gxvh\Python\cfgrib_test> pip install -U eccodes
Collecting eccodes
Installing collected packages: eccodes
  Attempting uninstall: eccodes
    Found existing installation: eccodes 1.7.1
    Uninstalling eccodes-1.7.1:
      Successfully uninstalled eccodes-1.7.1
Successfully installed eccodes-2.37.0

(venv) PS C:\Users\gxvh\Python\cfgrib_test> python
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import eccodes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gxvh\Python\cfgrib_test\venv\Lib\site-packages\eccodes\__init__.py", line 13, in <module>
    from .eccodes import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gxvh\Python\cfgrib_test\venv\Lib\site-packages\eccodes\eccodes.py", line 12, in <module>
    from gribapi import (
  File "C:\Users\gxvh\Python\cfgrib_test\venv\Lib\site-packages\gribapi\__init__.py", line 13, in <module>
    from .gribapi import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gxvh\Python\cfgrib_test\venv\Lib\site-packages\gribapi\gribapi.py", line 34, in <module>
    from gribapi.errors import GribInternalError
  File "C:\Users\gxvh\Python\cfgrib_test\venv\Lib\site-packages\gribapi\errors.py", line 16, in <module>
    from .bindings import ENC, ffi, lib
  File "C:\Users\gxvh\Python\cfgrib_test\venv\Lib\site-packages\gribapi\bindings.py", line 106, in <module>
    raise RuntimeError("Cannot find the ecCodes library")
RuntimeError: Cannot find the ecCodes library
>>>
```

### Version

2.37.0

### Platform (OS and architecture)

Python 3.11.9, Windows 10, [MSC v.1938 64 bit (AMD64)]

**Comment by iainrussell** [comment]
Hi @ghaarsma,

Yes, we changed how we package the ecCodes binaries, and the new method does not (and will not) support Windows, only Linux and MacOS. Our Windows support will be phased out over time, but I can suggest the following, with the most desirable first:
* try installing and using the [WSL](https://learn.microsoft.com/en-us/windows/wsl/about) (Windows Subsystem for Linux)
* try [conda](https://anaconda.org/conda-forge/python-eccodes), which will give you the binaries and the Python bindings (the Windows build will also stop becoming available from here, but not yet)
* stick with an older version of ecCodes
* try setting environment variable LD_LIBRARY_PATH to the path where the ecCodes binary library is installed inside ecmwflibs

I hope one of these solutions will allow you to continue to work with ecCodes!

**Comment by ghaarsma** [comment]
Hi @iainrussell,

With Windows still being a [very popular development](https://www.jetbrains.com/lp/devecosystem-2023/development/#os_devenv) platform, I'm hoping you (and everybody else at ECMWF) can reconsider.

It would only require 2 lines of code change in [bindings.py](https://github.com/ecmwf/eccodes-python/blob/75380c290a215d011d7fb60012d7bb7b925e9c78/gribapi/bindings.py#L94C1-L96C1) to make it work again with ecmwflibs.  I'll be happy to put together a PR for this change.

On the other hand, this would all be a moot point if [ecmwflibs](https://github.com/ecmwf/ecmwflibs) will not receive any future releases/upgrades.  I know that @b8raoult maintains that project and you have contributed in the past. Wheels for Python 3.12 (and updated eccodes) would be greatly appreciated.

I'll be happy to help with testing (which I understand can be difficult if you don't have access to the required setup) and contribute where I can.

**Comment by iainrussell** [comment]
Hi @ghaarsma,

Although you are correct in suspecting that we will no longer maintain ecmwflibs, I have some hopefully good news for you. Could you try to install the test version of the _brand new_ Windows ecCodes wheels from here: https://test.pypi.org/project/eccodes/#files
```
pip install -i https://test.pypi.org/simple/ eccodes
```
Note that this only contains wheels for Windows, not for Linux/Mac, because it is only for testing under Windows. If your tests are succesful then we will release this version in the next few days.

Cheers,
Iain

**Comment by ghaarsma** [comment]
Hi @iainrussell ,

Wow, that is excellent news. I was able to run the eccodes `selfcheck` under both Python 3.11 and 3.12 and that worked fine. 
I also re-tooled some of our internal Pipeline tests that take NOAA produced GRIB files and loaded them with `cfgrib` and compared them against saved Numpy result, which all tests passed.

The only very minor issue I saw is that `eccodes.codes_get_api_version()` still reported '2.38.3', Which I think it fine, but just letting you know.

```powershell
(venv) PS C:\Users\Python\cfgrib_test> python
Python 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
(venv) PS C:\Users\Python\cfgrib_test> pip install -U -i https://test.pypi.org/simple eccodes
Looking in indexes: https://test.pypi.org/simple, Requirement already satisfied: eccodes in c:\users\python\cfgrib_test\venv\lib\site-packages (2.38.3)
Collecting eccodes
  Downloading https://test-files.pythonhosted.org/packages/59/7d/287a578918ea2c273e571142ddf0cfc27d21289d49d0146e5eeba05e080b/eccodes-2.39.0-cp312-cp312-win_amd64.whl.metadata (12 kB)
Requirement already satisfied: numpy in c:\users\python\cfgrib_test\venv\lib\site-packages (from eccodes) (2.1.3)
Requirement already satisfied: attrs in c:\users\python\cfgrib_test\venv\lib\site-packages (from eccodes) (24.2.0)
Requirement already satisfied: cffi in c:\users\python\cfgrib_test\venv\lib\site-packages (from eccodes) (1.17.1)
Requirement already satisfied: findlibs in c:\users\python\cfgrib_test\venv\lib\site-packages (from eccodes) (0.0.5)
Requirement already satisfied: pycparser in c:\users\python\cfgrib_test\venv\lib\site-packages (from cffi->eccodes) (2.22)
Downloading https://test-files.pythonhosted.org/packages/59/7d/287a578918ea2c273e571142ddf0cfc27d21289d49d0146e5eeba05e080b/eccodes-2.39.0-cp312-cp312-win_amd64.whl (6.0 MB)
   ---------------------------------------- 6.0/6.0 MB 2.6 MB/s eta 0:00:00
Installing collected packages: eccodes
  Attempting uninstall: eccodes
    Found existing installation: eccodes 2.38.3
    Uninstalling eccodes-2.38.3:
      Successfully uninstalled eccodes-2.38.3
Successfully installed eccodes-2.39.0
(venv) PS C:\Users\Python\cfgrib_test> python -m eccodes selfcheck
Found: ecCodes v2.38.3.
Library: C:\Users\Python\cfgrib_test\venv\Lib\site-packages\eccodes\eccodes.dll
Definitions: /MEMFS/definitions
Samples: /MEMFS/samples
Your system is ready.
(venv) PS C:\Users\Python\cfgrib_test>
```

**Comment by iainrussell** [comment]
Thanks for testing, @ghaarsma. I have also managed to test it on my Windows machine (which I'd never used for Python before), so I will clean it up and we'll make a release early next week. The version number will be correct by then too :)

**Comment by ghaarsma** [comment]
Big thanks to @iainrussell for creating a Windows version as well for eccodes 2.39.0. I have closed out the issue.

One of the major advantages of Python is that it works so well across the various major eco systems (Windows, Linux, & Mac). This is crucial for us as we deploy on Linux, but our citizen developers are on Windows and typically don't have the know-how to run docker or WSL.

Kudos to Ian and his organization to keep eccodes supported on all major platforms.
