### ISSUE TITLE
Incorrect shortName / paramId

### ISSUE THREAD

**Issue by hugopendlebury** [ecmwf/eccodes-python#105]
### What happened?

Using eccodes 2.38.0 the shortName and paramId are wrong.

Actual results:
eccodes.__version__='2.38.0'
short_name='sde' 3066
**short_name='unknown' 0
short_name='unknown' 0**
short_name='10u' 165
short_name='10v' 166
short_name='tp' 228228
short_name='tcc' 228164
short_name='prmsl' 260074

Expected results:
eccodes.__version__='2.38.0'
short_name='sde' 3066
**short_name='tmax' 3015
short_name='tmin' 3016**
short_name='10u' 165
short_name='10v' 166
short_name='tp' 228228
short_name='tcc' 228164
short_name='prmsl' 260074

### What are the steps to reproduce the bug?

STEP1- Extract the zip file attached to some location e.g. /var/tmp/test_geavg.t00z.pgrb2a.0p50.f003

pip install eccodes==2.38.0

run the below

import eccodes

input_filename = "/var/tmp/test_geavg.t00z.pgrb2a.0p50.f003"

print(f"{eccodes.__version__=}")

with open(input_filename) as f:
    while(True):
        ptr = eccodes.codes_new_from_file(f, eccodes.CODES_PRODUCT_GRIB)
        if ptr is None:
            break
        short_name = eccodes.codes_get_string(ptr, "shortName")
        paramId = eccodes.codes_get_long(ptr, "paramId")
        print(f"{short_name=} {paramId}")
[test_data.zip](https://github.com/user-attachments/files/17146627/test_data.zip)

Run the code again with eccodes 2.37.0

Notice how tmax is "unknown" and has a paramId of 0 using version 2.38.0

### Version

2.38.0

### Platform (OS and architecture)

Ubuntu 20.04.06 LTS

### Relevant log output

```shell
eccodes.__version__='2.37.0'
short_name='sde' 3066
short_name='tmax' 3015
short_name='tmin' 3016
short_name='10u' 165
short_name='10v' 166
short_name='tp' 228228
short_name='tcc' 228164
short_name='prmsl' 260074
```

### Accompanying data

https://noaa-gefs-pds.s3.amazonaws.com/gefs.20240926/00/atmos/pgrb2ap5/geavg.t00z.pgrb2a.0p50.f003

### Organisation

BP

**Comment by shahramn** [comment]
We have documented the changes in paramId/shortName values here:
https://confluence.ecmwf.int/display/MTG2US/Changes+in+ecCodes+version+2.38.0+compared+to+the+previous+version

Here you can see 3015 and 3016 were removed (See section "Removed parameters / encodings or moved to another pseudo-centre")

**Comment by hugopendlebury** [comment]
In which case how can I process these historical public NOAA gribs ? I have checked the fields according to the wiki.

 grib_ls -w paramId=3015/3016 -p discipline,parameterCategory,parameterNumber,paramId test_geavg.
t00z.pgrb2a.0p50.f003
test_geavg.t00z.pgrb2a.0p50.f003
discipline         parameterCategory  parameterNumber    paramId
0                  0                  4                  3015
0                  0                  5                  3016
2 of 8 messages in test_geavg.t00z.pgrb2a.0p50.f003

As can be seen they have disipline 0, parameterCategory 0 and parameterNumber 4/5

Are you basically saying that we won't be able to eccodes 2.38.0 at all or will need to use different versions of eccodes to processes different gribs ?

**Comment by shahramn** [comment]
The WMO document says these two parameters are deprecated.
See https://library.wmo.int/idurl/4/35625
page 172

Quoting:
_Parameter deprecated. See Regulation 92.6.2 and use another parameter instead_

**Comment by shahramn** [comment]
But this should not have caused a failure ( shortName = unknown ). We will fix this using the legacy mechanism
i.e. Decoding should work but encoding will fail.

Many thanks for reporting this

**Comment by shahramn** [comment]
A new release of ecCodes will be made to address this (v2.38.2)

**Comment by shahramn** [comment]
Release version 2.38.3 is available from PyPI. Please try it
