### ISSUE TITLE
codes_set_values issue with second order packing type

### ISSUE THREAD

**Issue by maffrec** [ecmwf/eccodes-python#112]
### What happened?

Hi,
I'm attempting to set new values in a grib1 file packed in grid_second_order using eccodes.codes_set_values. 
When I'm doing it on a simple packed grib, everything works fine. If I want to do it on a second order packed grib, the command only works if I call it twice. 

Dummy example below for a grib containing a temperature forecast in Kelvin, trying to re-write it with Celsius degrees.
![grib_issue_second_order_packingType](https://github.com/user-attachments/assets/f8c23305-d026-477a-aeea-e4b0ccf50e53)

### What are the steps to reproduce the bug?

Reproducible with any grib1 file from ECMWF (for example T2m forecast)

Follow these steps to convert simple packing to second order packing and vice versa : https://confluence.ecmwf.int/display/UDOC/How+can+I+change+from+second+order+to+simple+packing+-+ecCodes+GRIB+FAQ 

`
import eccodes as ec

# With packingType=grid_simple
simple_grib = "/path_to_simple.grib"
f = open(simple_grib,'rb')
gid_simple = ec.codes_grib_new_from_file(f)
T_Kelvin = ec.codes_get_values(gid_simple)
print(T_Kelvin.mean()) # 287
T_Celsius = T_Kelvin - 273.15
ec.codes_set_values(gid_simple,T_Celsius)
print(ec.codes_get_values(gid_simple).mean()) # 14

# With packingType=grid_second_order
second_order_grib = "/path_to_second_order.grib"
f = open(second_order_grib,'rb')
gid_second_order = ec.codes_grib_new_from_file(f)
T_Kelvin = ec.codes_get_values(gid_second_order)
print(T_Kelvin.mean()) # 287
T_Celsius = T_Kelvin - 273.15
ec.codes_set_values(gid_second_order,T_Celsius)
print(ec.codes_get_values(gid_second_order).mean()) # 287 -> codes_set_values did not work the first time
ec.codes_set_values(gid_second_order,T_Celsius)
print(ec.codes_get_values(gid_second_order).mean()) # 14 -> codes_set_values worked the second time
`

### Version

v2.33.0

### Platform (OS and architecture)

Linux 4.18.0-348.12.2.el8_5.x86_64

**Comment by shahramn** [comment]
Dear @maffrec 
Can you please send us the GRIB1 file input file so we can reproduce the problem?
Just one message would suffice.
Thanks

**Comment by maffrec** [comment]
Dear @shahramn 
Here are the 2 GRIB1 file that I used (but I reproduced the issue with other files from ECMWF). 
[grib1_simple_and_secondorder_packingType.zip](https://github.com/user-attachments/files/17905910/grib1_simple_and_secondorder_packingType.zip)

**Comment by shahramn** [comment]
Another interesting point:
If you convert the GRIB1 file "second_order.grib" to GRIB edition 2, then the python script works fine.

```
% grib_set -s edition=2 second_order.grib second_order.grib2
# Modify the python script to use the new file second_order.grib2
% python3 encode.py 
287.77803913261465
14.628037606735763
14.628037606735763
```

So the bug is with the GRIB1 implementation

**Comment by shahramn** [comment]
JIRA ticket added: https://jira.ecmwf.int/browse/ECC-1986

**Comment by shahramn** [comment]
This bug has now been fixed. It will be in the next release of the ecCodes library (v2.40.0)
Many thanks
