### ISSUE TITLE
fatal flex scanner internal error--end of buffer missed

### ISSUE THREAD

**Issue by meteoDaniel** [ecmwf/eccodes-python#113]
### What happened?

I updated my project to the latest eccodes version from 2.30.2 to 2.39.0. Now I am receiving 
``` 
fatal flex scanner internal error--end of buffer missed
``` 
error while parsing ecmwf open data forecast. 

### What are the steps to reproduce the bug?

I am using   `python:3.10-slim`  Docker image as basis and I removed all manually installed eccodes binary. 

```bash
root@8354140fb24b:/app# python -m eccodes selfcheck
Found: ecCodes v2.39.0.
Library: /usr/local/lib/python3.10/site-packages/eccodes.libs/libeccodes-e85d471c.so
Definitions: /app/eccodes_definitions/dmi_grib_definitions:/app/eccodes_definitions/definitions.edzw-2.30.2-1:/MEMFS/definitions
Samples: /MEMFS/samples
Your system is ready.
```

As you can see I am having some additional definitions, removing them does not change anything to the fact that using:  

```python
import xarray
data = xarray.open_mfdataset(
                local_file_list,
                engine="cfgrib",
                parallel=True,
                concat_dim="valid_time",
                combine="nested",
                backend_kwargs={
                    "indexpath": "",
                    "errors": "ignore",
                    "filter_by_keys": {'typeOfLevel': 'mostUnstableParcel', 'shortName': 'mucape'},                },
            )
```
leads to the issue named above. 

Using `cfgrib.open_datasets()`works fine.

By changing the ECCODES_DEFINITIONS_PATH I am receiving different Errors.

### Version

v2.39.0

### Platform (OS and architecture)

python3.10-slim Docker image 

### Relevant log output

```shell
ECCODES ERROR   :  grib_handle_create: Cannot create handle, no definitions found
ECCODES ERROR   :  grib_handle_new_from_file_multi: Cannot create handle
ECCODES ERROR   :  grib_handle_create: Cannot create handle, no definitions found
ECCODES ERROR   :  grib_handle_new_from_file_multi: Cannot create handle
fatal flex scanner internal error--end of buffer missed
ECCODES ERROR   :  Parser: syntax error at line 1 of /MEMFS/definitions/grib2/boot.def
ECCODES ERROR   :  ecCodes Version: 2.39.0
```

### Accompanying data

https://data.ecmwf.int/forecasts/20241129/00z/ifs/0p25/oper/ 

### Organisation

alitiq

**Comment by meteoDaniel** [comment]
Is anyone here, and knows something about this issue?

**Comment by meteoDaniel** [comment]
> Are you launching multiple threads to decode GRIB messages?

I think this is what happens when calling `parallel=True` , by default dask.delayed is used

**Comment by meteoDaniel** [comment]
@shahramn  setting parallel to False does not raise the issue. Does this help to understand the issue?

**Comment by shahramn** [comment]
The eCodes library needs to be built with thread-safety (mutexes). So if you are building it using cmake, add the following option:
**-DENABLE_ECCODES_THREADS=ON**

**Comment by meteoDaniel** [comment]
So I reverted my changes and added the installtion of eccodes again: 

```Dockerfile
RUN wget https://cmake.org/files/v3.20/cmake-3.20.1.tar.gz
RUN tar -xzvf cmake-3.20.1.tar.gz
WORKDIR cmake-3.20.1/
RUN apt-get update && apt-get install --fix-missing -yqq
RUN ./bootstrap
RUN make -j$(nproc) && make install

WORKDIR /

RUN curl https://confluence.ecmwf.int/download/attachments/45757960/eccodes-2.39.0-Source.tar.gz?api=v2 -o /tmp/eccodes-2.39.0-Source.tar.gz
RUN tar -xzf /tmp/eccodes-2.39.0-Source.tar.gz
RUN mkdir build \
    && cd build \
    && cmake /eccodes-2.39.0-Source -DCMAKE_INSTALL_PREFIX=/usr/local/share/eccodes -DENABLE_ECCODES_THREADS=ON -DENABLE_JPG=ON \
    && make install


COPY ./requirements.txt /opt/requirements.txt
RUN pip3 install --no-cache-dir -r /opt/requirements.txt --no-binary eccodes
```

I am using eccodes=2.39.0 in my requirements.txt here. 

Now the script terminates without any further information. Same with using cfgrib: 

![image](https://github.com/user-attachments/assets/669f20f2-9afb-483c-8b81-fa412ac4748f)


Running `python -m eccodes selfcheck`


```python
root@6c0426ac3fbb:/app# python -m eccodes selfcheck
/usr/local/lib/python3.10/site-packages/gribapi/__init__.py:23: UserWarning: ecCodes 2.38.0 or higher is recommended. You are running version 2.28.0
  warnings.warn(
Found: ecCodes v2.28.0.
Library: libeccodes.so.0
Definitions: /app/eccodes_definitions/dmi_grib_definitions:/app/eccodes_definitions/definitions.edzw-2.36.0-2:/eccodes-2.39.0-Source/definitions/:/usr/share/eccodes/definitions
Samples: /usr/share/eccodes/samples
Your system is ready.
```
Where does this version is coming from? What kind of dependency can lead to this downgrade?

**Comment by meteoDaniel** [comment]
Setting `ECCODES_PYTHON_USE_FINDLIBS` to 0 will change the output of `python -m eccodes selfcheck` to: 

```python
root@7168fbbebeda:/app# export ECCODES_PYTHON_USE_FINDLIBS=0
root@7168fbbebeda:/app# python -m eccodes selfcheck
Found: ecCodes v2.39.0.
Library: /usr/local/lib/python3.10/site-packages/eccodes.libs/libeccodes-e85d471c.so
Definitions: /app/eccodes_definitions/dmi_grib_definitions:/app/eccodes_definitions/definitions.edzw-2.36.0-2:/eccodes-2.39.0-Source/definitions/:/MEMFS/definitions
Samples: /MEMFS/samples
Your system is ready.

```


But this does not change anythin that the script just terminates without any excpetion.

**Comment by meteoDaniel** [comment]
@alexamici @iainrussell  does anyone of you know what's going on here?

Where is version 2.28. coming from?

**Comment by meteoDaniel** [comment]
I really want to get this software running, but I  do no thave any experience in C/C++ and can't figure out where the old version is coming from. 
Is anyone of you able to build the image according to the provided Dockerfile?

So what has changed from version 2.30.2. to the most current ones?

Because of such problems, I am always afraid of updating eccodes and the related software stack.

**Comment by iainrussell** [comment]
Hi @meteoDaniel,

We believe this problem comes from the new ecCodes binary wheel that now ships by default with eccodes-python. We did not build this wheel with thread-safety enabled, which is very likely the cause of this problem. We will make a new release in the next day or two with thread-safety enabled, and then this problem should disappear.

**Comment by meteoDaniel** [comment]
Dear @iainrussell , thanks for your reply. That sounds like a good approach. 

Will have thread-safety enabled some downsides for other users?

And do you have an explanation for the appearance of the old eccodes version? Am I do sth. wrong here?
Best regards and thanks a lot.

**Comment by iainrussell** [comment]
Well, thread-safety gives a small performance penalty (I think around 5% or similar, depending on usage), but of course the use of threads gives more advantage then that. And since this library will be used in many contexts, thread-safety is a very good idea :)

As for the old version of ecCodes, it looks like that Docker image is based on Debian Bullseye. According to the package catalogue, 2.28 is the latest version of ecCodes that they have for any Debian build: https://packages.debian.org/search?keywords=eccodes&searchon=names&suite=stable&section=all

Maybe they stopped creating Debian packages with 2.28 (it was always a third-party maintainer, not ECMWF, who built such packages).

**Comment by meteoDaniel** [comment]
@iainrussell  thanks for the explanation. 
How can I tell eccodes to use the manually compiled version? Or is this impossible due to the existing binaries?

**Comment by meteoDaniel** [comment]
@iainrussell  I solved it. 
I removed: `-DCMAKE_INSTALL_PREFIX=/usr/local/share/eccodes` from the installation. Now selfcheck finds the right version.

**Comment by shahramn** [comment]
Please try the new version **2.39.1** from PyPI. This has the thread-safety option enabled

**Comment by meteoDaniel** [comment]
Awesome, everything works right now as expected ! :-)
