### ISSUE TITLE
import "from .bindings import ENC, ffi, lib" error 

### ISSUE THREAD

**Issue by pletzer** [ecmwf/eccodes-python#13]
Hi,

I did a "conda install -c conda-forge eccodes". The his installed successfully the command line tools "grib_ls, grib_dump...". However, "python -c eccodes" failed with 

ImportError: No module named eccodes

Then installed eccodes via pip:
pip install eccodes-python

and now I'm getting 
(eccodes) niwa-1019500~/grib$ python -c "import eccodes"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/eccodes/__init__.py", line 4, in <module>
    from .eccodes import *
  File "/usr/local/lib/python2.7/site-packages/eccodes/eccodes.py", line 1, in <module>
    from gribapi import __version__
  File "/usr/local/lib/python2.7/site-packages/gribapi/__init__.py", line 1, in <module>
    from .gribapi import *  # noqa
  File "/usr/local/lib/python2.7/site-packages/gribapi/gribapi.py", line 21, in <module>
    from .bindings import ENC, ffi, lib
  File "/usr/local/lib/python2.7/site-packages/gribapi/bindings.py", line 34, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined

(eccodes) niwa-1019500~/grib$ conda list
# packages in environment at /Users/pletzera/miniconda3/envs/eccodes:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h01d97ff_1    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
curl                      7.65.3               h22ea746_0    conda-forge
eccodes                   2.14.1               ha74ff94_3    conda-forge
hdf4                      4.2.13            h84186c3_1003    conda-forge
hdf5                      1.10.5          nompi_h3e39495_1104    conda-forge
jasper                    1.900.1           h636a363_1006    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libaec                    1.0.4                h0a44026_0    conda-forge
libcurl                   7.65.3               h16faf7d_0    conda-forge
libcxx                    9.0.0                h89e68fa_1    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libgfortran               4.0.0                         2    conda-forge
libnetcdf                 4.7.1           nompi_hec86efb_102    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
llvm-openmp               9.0.0                h40edb58_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
openssl                   1.1.1d               h0b31af3_0    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge

Thanks for any help.

**Comment by alexamici** [comment]
@pletzer *eccodes-python* supports only *Python 3* and you appear to be running a *Python 2* *conda* environment.

Create a *Python 3* environment and try again.

**Comment by pletzer** [comment]
Thanks, works now....
