### ISSUE TITLE
Selfcheck warning recommends ecCodes 2.17.0 or higher, but latest available release is 2.16.0

### ISSUE THREAD

**Issue by SpiralArray** [ecmwf/eccodes-python#17]
Using Anaconda3, I installed eccodes-2.15.0 (latest avail from conda-forge), then followed  instructions to install eccodes-python with Fast CFFI bindings:
$ git clone https://github.com/ecmwf/eccodes-python
$ cd eccodes-python
$ pip install -e .

I then had to modify builder.py so that **python builder.py** would find my eccodes.h file and build properly -
ffibuilder.set_source(
    "gribapi._bindings", "#include <**/home/user/anaconda3/include/eccodes.h**>", libraries=["eccodes"],
)

Now when I run a selfcheck or >>>import eccodes, I get the warning:

(base) [user]:~]$ python -m eccodes selfcheck
**Warning: ecCodes 2.17.0 or higher is recommended. You are running version 2.15.0**
Found: ecCodes v2.15.0.
Your system is ready.

I see at https://confluence.ecmwf.int//display/ECC/Releases that the latest release is v2.16.0, which was released yesterday, 13 Jan 2020.

I then located the following in gribapi/__init__.py:min_reqd_version_str = "2.17.0". Should this be changed to read "2.15.0"?

Thanks!

**Comment by shahramn** [comment]
Please get the "master" branch and not "develop"
________________________________
