### ISSUE TITLE
Windows Error: exit code -1073741819

### ISSUE THREAD

**Issue by afDeathscythe** [ecmwf/eccodes-python#20]
Hi,

I found some threads according to this error but I could not really get an answer out of them:
So I am using the following on my Windows 10 machine with Anaconda as standard Python Interpreter:

-eccodes v2.16.0
-python-eccodes v2020.01.0

I solved the issue with ECCODES_DEFINITION_PATH in my PyCharm Environment but now it just exits like this:

Process finished with exit code -1073741819 (0xC0000005)

Any ideas how you can get it working? Thanks in advance!

**Comment by shahramn** [comment]
What is the value of the environment variable ECCODES_DEFINITION_PATH?

**Comment by shahramn** [comment]
I think this issue is fixed now. Please retry and if it persists, re-open the issue
