### ISSUE TITLE
Add binding to grib_multi_support_reset_file 

### ISSUE THREAD

**Issue by alexamici** [ecmwf/eccodes-python#26]
In order to use multi_support play well with random access of MULTI-FIELD messages in *cfgrib* I need to reset the multi_support state. At the moment I'm using `grib_multi_support_reset_file` that appear to work well, but it is not available in `eccodes-python`.

**Comment by shahramn** [comment]
Dear Alessandro,
I will add this function in the next release of eccodes-python

**Comment by alexamici** [comment]
I'll release a new version of *cfgrib* using this soon. All needed APIs are now supported. Many thanks!
