### ISSUE TITLE
Reappearance of segfault in saving non-double arrays, as in #30

### ISSUE THREAD

**Issue by pp-mo** [ecmwf/eccodes-python#34]
On removing the workaround we introduced in [iris-grib#208](https://github.com/SciTools/iris-grib/pull/208), the original signature problem as reported in #30, seems to have reappeared.

Context: 
  * running under Linux, via Travis 
  * The error is seen here in the Travis testing log : https://travis-ci.org/github/SciTools/iris-grib/jobs/731255839#L1237
  * The testcode that triggers this is in [this test](https://github.com/SciTools/iris-grib/blob/master/iris_grib/tests/unit/save_rules/test_data_section.py#L155)
  * The versions of all packages installed can be seen from [the "conda list" command in the Travis log](https://travis-ci.org/github/SciTools/iris-grib/jobs/731255839#L464) 
      * ( **N.B.** open the collapsed section to view installed packages )

**Comment by shahramn** [comment]
Dear Patrick,
This is fixed in the next release (v2.19.0) Hopefully out in October

**Comment by pp-mo** [comment]
Ok thanks @shahramn , I think that means there is no real problem here.

**Comment by shahramn** [comment]
We have released the new python bindings for ecCodes (as well as a new library version)

**Comment by pp-mo** [comment]
@shahramn thanks for the update.
We will check it out !

**Comment by shahramn** [comment]
Please let me know if all IRIS tests pass

**Comment by pp-mo** [comment]
We finally got to cut [iris-grib v0.16.0](https://github.com/SciTools/iris-grib/releases/tag/v0.16.0)
(it's been waiting for [Iris 3.0](https://github.com/SciTools/iris/releases/tag/v3.0.0))

All looking fine now, thanks @shahramn .

**Comment by shahramn** [comment]
Glad to hear it. And thank you for your patience
