### ISSUE TITLE
Building eccodes

### ISSUE THREAD

**Issue by akashpulimel** [ecmwf/eccodes-python#35]
Hello all,

I'm trying to install eccodes on my windows 10 system by following the instructions provided in the GitHub page(https://github.com/ecmwf/eccodes). While running the -DCMAKE_INSTALL_PREFIX line of the code (in command prompt), it starts to build but soon exits with the following error:

"CMake Error at cmake/ecbuild_log.cmake:196 (message):
  CRITICAL - Failed to replace windows symlinks.  output=[] error=[/bin/bash:
  E:/Akash/eccodes-2.18.0-Source/cmake/ecbuild_windows_replace_symlinks.sh:
  No such file or directory

  ]
Call Stack (most recent call first):
  cmake/ecbuild_check_os.cmake:450 (ecbuild_critical)
  cmake/ecbuild_system.cmake:265 (include)
  CMakeLists.txt:25 (include)

-- Configuring incomplete, errors occurred!
See also "E:/Akash/build/CMakeFiles/CMakeOutput.log".

  

I'm using cmake-3.18.3-win64-x64, eccodes-2.18.0-Source (downloaded from https://confluence.ecmwf.int/display/ECC/Releases and extracted as instructed), I have installed Ubuntu from windows store and I'm building in a clean directory.  'CMakeOutput.log' and 'ecbuild.log' files are also attached here for your reference.
[CMakeOutput.log](https://github.com/ecmwf/eccodes-python/files/5338439/CMakeOutput.log)
.
[ecbuild.log](https://github.com/ecmwf/eccodes-python/files/5338444/ecbuild.log)

If anybody has any solutions/suggestions on this, please help. 

Thanks, 
Akash

**Comment by shahramn** [comment]
Windows is not fully supported

**Comment by MRPHarris** [comment]
Hi @akashpulimel, did you ever find a solution to this issue? I am trying to compile on windows and have run into the exact same error.
