### ISSUE TITLE
`headers_only` not used in `grib_new_from_file`

### ISSUE THREAD

**Issue by alexamici** [ecmwf/eccodes-python#40]
In https://github.com/ecmwf/eccodes-python/blob/develop/gribapi/gribapi.py#L402 and following the `headers_only` keyword argument is not passed to the C-bindings.

This appears deliberate, so maybe I'm missing something, but the functionality is not available any more.

I suggest to either add the functionality back or update the function documentation, and probably add a warning.

**Comment by shahramn** [comment]
This feature was experimental and only (just) worked for GRIB edition 1. In fact we should have never released it in the API
