### ISSUE TITLE
Issue with  codes_grib_find_nearest not working

### ISSUE THREAD

**Issue by ComputerU** [ecmwf/eccodes-python#49]
Hi,

My system:
Ubuntu 20.04
Eccodes 1.1.0
Eccodes-python 0.9.9

I'm trying to read a grib file and use the following. It seems to fail with the following:

![image](https://user-images.githubusercontent.com/80340633/111157987-71250080-858f-11eb-9765-48c8b8bc7f26.png)

Code:
from __future__ import print_function
import traceback
import sys
from eccodes import *
 
INPUT = '/home/james/Desktop/File'
VERBOSE = 1  # verbose error reporting

lat=55.1
lon=-3.1
f = open(INPUT, 'rb')
gid = codes_grib_new_from_file(f)

nearest = codes_grib_find_nearest(gid, lat, lon)

**Comment by ComputerU** [comment]
I took this example from the examples page on ECMWF:
https://confluence.ecmwf.int/display/ECC/grib_nearest

Could this because I'm using python 3 and not python 2?

**Comment by shahramn** [comment]
Can you share your input file with me? so I can reproduce this error?
