### ISSUE TITLE
Typo in gribapi.py causes AttributeError when calling codes_index_get_double

### ISSUE THREAD

**Issue by gernotgeppert** [ecmwf/eccodes-python#51]
I suppose it should read `grib_index_get_double` instead of `grib_index_get_doule`.

https://github.com/ecmwf/eccodes-python/blob/8b997a5691677dd835c5278b171c6acba851d584/gribapi/gribapi.py#L1451

**Comment by shahramn** [comment]
Well spotted. Many thanks. I will fix this at once and add a test

**Comment by shahramn** [comment]
A JIRA issue has been created for this: See https://jira.ecmwf.int/browse/ECC-1226

**Comment by gernotgeppert** [comment]
Thanks for the quick fix! Did it make it into 1.2.0 on pypi by any chance?

**Comment by shahramn** [comment]
Unfortunately this was discovered after we released v1.2.0. An hour or so earlier would have made it.
