### ISSUE TITLE
eccodes Table issues

### ISSUE THREAD

**Issue by LudwigGoh** [ecmwf/eccodes-python#55]
I have used ecCodes for a while, and recently I tried to use it to decode some GNSS RO data from NOAA GDAS. I got some error message when I try to use
the command line
bufr_filter keys.filter gfs.t06z.gpsro.tm00.bufr_d.365
to grab the wanted subset, I got error like
 
1 of 1 total messages in 1 files
ECCODES ERROR   :  unable to get descriptor 063000 from table
ECCODES ERROR   :  unable to get descriptor 063000 from table
ECCODES ERROR   :  unable to get descriptor 361160 from table
ECCODES ERROR   :  unable to get descriptor 361160 from table
ECCODES ERROR   :  unable to get descriptor 102000 from table
ECCODES ERROR   :  unable to get descriptor 102000 from table
ECCODES ERROR   :  unable to get descriptor 063255 from table
ECCODES ERROR   :  unable to get descriptor 063255 from table
ECCODES ERROR   :  hash_array: no match for sequences=361160
ECCODES ERROR   :  Error while setting key unpack (Hash array no match)
ERROR: Hash array no match
 
The keys.filter looks like
set unpack=1;
set doExtractSubsets=1;
write "[bufrHeaderCentre:i]_[dataCategory].bufr[editionNumber]";
 
I know it’s related to some tables, but I don’t know how to find those table, and how to put them in the right place. Would you please help me to resolve the issue. Thank you very much in advance.

**Comment by shahramn** [comment]
See https://confluence.ecmwf.int/display/UDOC/Local+configuration+-+ecCodes+BUFR+FAQ
Try the "strace" trick to see what tables (local ones) ecCodes is attempting to load
