### ISSUE TITLE
data file tiggelam_cnmc_sfc.grib2 not included in released tar file eccodes-1.4.0.tar.gz 

### ISSUE THREAD

**Issue by jdkloe** [ecmwf/eccodes-python#59]
MANIFEST.in contains the line "recursive-include tests *.grib" and therefore only includes files with extension .grib.
However, currently the file below test/sample-data has extension .grib2:
"tests/sample-data/tiggelam_cnmc_sfc.grib2"

Therefore this file is not included in the release tar file eccodes-1.4.0.tar.gz 
and this causes the 2 failures in the provided test suite when running them using the pytest-3 command:
================================ short test summary info =================================
FAILED tests/test_eccodes.py::test_count_in_file - FileNotFoundError: [Errno 2] No such...
FAILED tests/test_eccodes.py::test_extract_offsets - gribapi.errors.IOProblemError: Inp...
======================== 2 failed, 58 passed, 5 warnings in 2.18s =============================

So please update your manifest file to solve this issue.

**Comment by shahramn** [comment]
I've just checked both the ZIP file and the TAR and they both contain the aforementioned grib file.
https://github.com/ecmwf/eccodes-python/archive/refs/tags/1.4.0.zip
https://github.com/ecmwf/eccodes-python/archive/refs/tags/1.4.0.tar.gz

Am I missing something?

**Comment by shahramn** [comment]
Looks like the one on the PyPI site:
 
https://pypi.org/project/eccodes/#files

does NOT have it. Thanks for pointing that out

**Comment by jdkloe** [comment]
Yes, I was referring to the pypi copy.

**Comment by jdkloe** [comment]
The versions that I used are:
eccodes v2.24.0
(python) eccodes-1.4.0
python3.10
Fast bindings enabled.

**Comment by shahramn** [comment]
I have fixed the MANIFEST file to include the correct extension

**Comment by shahramn** [comment]
This has now been fixed
