### ISSUE TITLE
Can eccodes decode buffr radar image?

### ISSUE THREAD

**Issue by chris3522** [ecmwf/eccodes-python#60]
Hi,
Can Eccodes decode bufr rain radar images?
Regards

**Comment by chris3522** [comment]
Yes but the size is 7 MB, I can't post it. 
Here a link to dowload it: 
https://wetransfer.com/downloads/33653a17929f54c39390751be01b94e420220121184617/3a721d660d30491ea3bd54c6b3c566d320220121184712/cfd1ea

**Comment by shahramn** [comment]
So I see this BUFR file is using LOCAL i.e., NON-STANDARD descriptor codes.
For example 029192; this is not a WMO standard descriptor code.

For ecCodes to decode this file, you will need to contact the supplier and ask them for their local tables.

**Comment by shahramn** [comment]
According to the WMO, the use of local tables in messages intended for non-local or international exchange is **strongly discouraged**.

**Comment by shahramn** [comment]
Also see https://confluence.ecmwf.int/display/UDOC/Local+configuration+-+ecCodes+BUFR+FAQ

**Comment by chris3522** [comment]
Ok thanks.
