### ISSUE TITLE
Please use the warnings library for selfcheck

### ISSUE THREAD

**Issue by dsjstc** [ecmwf/eccodes-python#64]
On Ubuntu 21.04 (a very common docker environment), the easily available version of libeccodes is version 2.20.0.  Any pip-installed version of eccodes-python newer than 1.1.0 gives the following warning at import time:

`Warning: ecCodes 2.21.0 or higher is recommended. You are running version 2.20.0`

It would be really nice if this warning could be emitted by the warnings library, so it would be possible to catch it if desired, with code like this:

```
import warnings
with warnings.catch_warnings():
    import eccodes
```

In the meantime, if I don't want this (practically unaddressable) warning emitted by my script, I see no choice but to revert to `pip install eccodes==1.1.0`.

**Comment by shahramn** [comment]
The ecCodes library is now v2.26.0. Can I ask why your library version is so old?
Version 2.20.0 is from January 2021

See https://confluence.ecmwf.int/display/ECC/History+of+Changes

**Comment by uwefladrich** [comment]
I have run into the same issue. Writing warnings to `stdout` via `print` messes up the output of tools that import eccodes. Writing via the Python standardlib `warnings` module would make the warnings appear on `stderr` (by default), which would also allow for shell redirection.

Pointing to newer versions of eccodes does not really address the issue.

**Comment by uwefladrich** [comment]
Great, thanks a lot! :+1:

**Comment by dsjstc** [comment]
Cool, thanks!
