### ISSUE TITLE
Please support Python 3.10 (and 3.11)

### ISSUE THREAD

**Issue by equaeghe** [ecmwf/eccodes-python#69]
Some Linux distributions are using Python 3.10 as their default Python now, and it becomes inconvenient to install and use older versions. Would it be possible to support more recent versions of Python, such as 3.10 and 3.11?

**Comment by iainrussell** [comment]
Hello @equaeghe,

Could you be more precise in terms of how you are trying to install or use ecCodes? I just successfully installed it into a Python 3.11 environment (using 'pip install eccodes') and ran the self-check. Are you using conda-forge perhaps?

**Comment by equaeghe** [comment]
I think https://github.com/ecmwf/eccodes-python/commit/1f6d1ff09b1243034ec191daabd8739e1dfddb37 of today fixed this.
