### ISSUE TITLE
Handling segmentation faults

### ISSUE THREAD

**Issue by jarethholt** [ecmwf/eccodes-python#7]
When using eccodes through Python to explore a grib file, I can often get "Segmentation Fault (core dumped)" errors. This kicks me out of the interpreter, and I lose any variables I had been working with. The most replicable instances I have found are trying to open an already-open grib file, or trying to close/release/delete an already closed grib file, index file, or iterator. A more subtle segmentation fault comes from trying to delete an iterator associated with a closed grib file. I also run into cases where looping over codes_keys_iterator, I will hit a number of known errors (ArrayTooSmallError, wrong size for pl, Function not yet implemented). Attempting to delete the iterator will segfault in some cases but not others.

Is there any functionality in SWIG to handle these kinds of seg faults? What about adding sanity checks to objects within Python? I have had some success in wrapping objects using contextlib, but a) that's python3 only and b) it ensures safety by opening and closing the grib files every time, which can hamper exploring them and will sometimes mess up loops. I'd be happy to try to help from the Python side, but I have no experience in C/C++/SWIG.

**Comment by shahramn** [comment]
Dear Jareth,
Thanks for your comment. It is preferable if you report issues/questions to our Software Support team at ECMWF.
Can I please ask you to forward your issue with reproducible test cases to:
    Software.Support@ecmwf.int

Cheers

**Comment by jarethholt** [comment]
Sure. How should I go about making test cases? I have a few of my own grib files to work with, but is there a standard one I can use for illustration purposes?

**Comment by shahramn** [comment]
First of all the eccodes-python package here is for Python 3 only. So you can write your test cases using Python 3 syntax etc.
Also if the problems you noted are specific to input GRIB files you have, please provide the smallest subset which reproduces the problem

**Comment by jarethholt** [comment]
I think most of the things I was going to comment on will be handled by the "High-level pythonic interface". That appears to implement a context manager similar to what I was writing. I might get in touch with Software.Support about a particular key error, but otherwise leave this alone.
