### ISSUE TITLE
`codes_get` silently returns `None` for unsupported key types

### ISSUE THREAD

**Issue by gernotgeppert** [ecmwf/eccodes-python#71]
Calling `eccodes.codes_get` for a key with a type that is not one of `GRIB_TYPE_LONG`, `GRIB_TYPE_DOUBLE`, `GRIB_TYPE_STRING` returns `None`. It should probably raise an exception instead.

```
import os
os.environ['ECCODES_DEFINITION_PATH']='definitions.edzw-2.27.0-1'

import eccodes

with open('icon_grib_template') as f:
    gid = eccodes.codes_grib_new_from_file(f)
print(eccodes.codes_get(gid, 'uuidOfHGrid'))      # uuidOfHGrid has type GRIB_TYPE_BYTES
eccodes.codes_release(gid)

# prints None
```

eccodes 2.27.0
eccodes-python 1.5.0

[definitions-edzw.zip](https://github.com/ecmwf/eccodes-python/files/10806231/definitions-edzw.zip)
[icon_grib_template.zip](https://github.com/ecmwf/eccodes-python/files/10805879/icon_grib_template.zip)

**Comment by shahramn** [comment]
Good point. I will look into it.

By the way you can always do:
```
>>> print(eccodes.codes_get(gid, 'uuidOfHGrid', str))
08b1e836bc6911e1951fb51b5624ad8d
```
or
```
>>> print(eccodes.codes_get_string(gid, 'uuidOfHGrid'))
08b1e836bc6911e1951fb51b5624ad8d
```

**Comment by gernotgeppert** [comment]
Thank you. I didn't think of `codes_get(gid, 'uuidOfHGrid', str)`.

But anyway, my use case so far was
```
attrs = {}
for key in keys:
    try:
        attrs[key] = eccodes.codes_get(gid, key)
    except ... :
        # handle errors
```
and `codes_get(gid, 'uuidOfHGrid', str)` won't help because I can't use `codes_get_native_type(gid, 'uuidOfHGrid')` to get the type before the call to `codes_get` (#70).
