### ISSUE TITLE
Add method to access the result of the json bufr_dump

### ISSUE THREAD

**Issue by sandorkertesz** [ecmwf/eccodes-python#79]
### Is your feature request related to a problem? Please describe.

At the moment, only the `bufr_dump` command line tool can generate a json dump for a BUFR message. If I want to use the dump in Python I need to run the command line tool e.g. with `subprocess`, redirect the output to a (json) file and read it back as json. 

### Describe the solution you'd like

It would be really useful if there was a method in the Python API generating the same dump as a dictionary. 

### Additional context

It would help the implementation of https://github.com/ecmwf/earthkit-data/issues/115

### Organisation

ECMWF

**Comment by shahramn** [comment]
```
import eccodes
import sys

eccodes.codes_set(bid, 'unpack', 1)
eccodes.codes_dump(bid, sys.stdout, "json") 
```

**Comment by shahramn** [comment]
You could then take the JSON output and convert it to a dictionary

**Comment by sandorkertesz** [comment]
Unfortunately, it does not work. I use ecCodes Version 2.30.2.

<img width="808" alt="image" src="https://github.com/ecmwf/eccodes-python/assets/9033020/dc98ea5c-071e-49fa-8046-fcbf4e59ccec">

**Comment by sandorkertesz** [comment]
However, this code works in the same environment:

```python
h = eccodes.codes_bufr_new_from_samples("BUFR4")
eccodes.codes_set(h, "unpack", 1)
p = "dump_bufr_1.txt"
with open(p, "w") as fout:
    eccodes.codes_dump(h, fout, "json")
eccodes.codes_release(h)
```

**Comment by sandorkertesz** [comment]
When I run the `sys.stdout` version as as script it works. So the problem seems to be related to **jupyter notebooks**.
