### ISSUE TITLE
Enabling thread safety using pip

### ISSUE THREAD

**Issue by dhah229** [ecmwf/eccodes-python#83]
### Is your feature request related to a problem? Please describe.

As mentioned in https://github.com/ecmwf/cfgrib/issues/110#issuecomment-705544248, I am unable to open multiple datasets with `xarray.open_mfdataset()` with `parallel=True`. From what I understand, we can install [eccodes from conda to fix this problem](https://github.com/ecmwf/cfgrib/issues/110#issuecomment-708417516). Is it possible to install thread safety enabled `eccodes` without using conda? I am currently using a docker container to process my work. If not what other alternatives do I have?

**Comment by martincjespersen** [comment]
I am also in the need for being able to use parallel=True without using conda. Is there any status on this @shahramn ?

**Comment by shahramn** [comment]
If you build your own ecCodes, enable the mutexes for thread safety
cmake /path/to/eccodes -D ENABLE_ECCODES_THREADS=ON

See https://confluence.ecmwf.int/display/ECC/ecCodes+installation
