### ISSUE TITLE
version coherence with eccodes

### ISSUE THREAD

**Issue by kmuehlbauer** [ecmwf/eccodes-python#9]
Trying to create bindings for `ecCodes 2.13.1` using `eccodes-python 0.9.3` breaks due to 

```
gribapi/_bindings.c:5679:12: error: 'GRIB_FUNCTIONALITY_NOT_ENABLED' undeclared
```

How does one know which version of `ecCodes` the `eccodes-python` packages needs?

**Comment by shahramn** [comment]
You need the latest ecCodes i.e. v2.14.0

https://confluence.ecmwf.int/display/ECC/ecCodes+version+2.14.0+released
Apologies for not having made it clear
________________________________

**Comment by kmuehlbauer** [comment]
@shahramn No worries. But how should running into this sort of error be prevented?

If the user installs some `ecCodes` version and then `pip install eccodes-python` this can break if the correct `ecCodes` version is not available.

Would it be possible to check for the needed version of `ecCodes` and issue a warning/error with additional guidelines?

**Comment by alexamici** [comment]
@shahramn the version check that you added here:

https://github.com/ecmwf/eccodes-python/blob/a896f608df687a7794c5a8c44fb219634eed03a2/gribapi/__init__.py#L5

looks way too strict. The failure reporte in this issue happen only when you try to build the bindings, but by raising and exception it is not possible to use eccodes-python even with the ABI, that is what most of current users do.

At the moment for example the whole *cfgrib* test suite would pass with version 2.12.0 if it were not for this check.

Can you change the raise to a simple print, please?
