### ISSUE TITLE
contribution guide refers to removed files

### ISSUE THREAD

**Issue by ejd** [ecmwf/eccodes-python#90]
### What maintenance does this project need?

The [Get Started!](https://github.com/ecmwf/eccodes-python/blob/9f9d8fd331ef47fc25cc3510ca8b2a52f1bd2aaa/CONTRIBUTING.rst#get-started) section of `CONTRIBUTING.rst` refers to `ci/requirements-tests.txt` but the entire contents of the `ci` directory was removed back in 2021 by a6cff6a.  Was the removal a mistake?  Or is the contribution guide out of sync with the project's current practices?

### Organisation

Self

**Comment by shahramn** [comment]
Thanks for spotting this. I will restore those 2 files

**Comment by ejd** [comment]
@shahramn Hi, thank you for addressing this.  I'm sorry I didn't mention this in the original issue, but I think the real fix is to revert the entirety of a6cff6a; to restore all of the files removed by that commit.  

The `ci/requirements-*.txt` files are built from the `ci/requirements-*.in` files by `pip-compile` via `make update-req`.  Without the `*.in` files, you can't generate new `*.txt` files with up-to-date versions of the dependencies.

**Comment by shahramn** [comment]
Apologies. I will restore the files. In the future we will switch to using toml
